//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DevextremeXPOCRUD.Models.XPO.PracticeDB
{

    [Persistent(@"PRODUCT")]
    public partial class XPPRODUCT : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fNAME;
        public string NAME
        {
            get { return fNAME; }
            set { SetPropertyValue<string>(nameof(NAME), ref fNAME, value); }
        }
        int? fPRICE;
        public int? PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<int?>(nameof(PRICE), ref fPRICE, value); }
        }
        int? fCategoryId;
        public int? CategoryId
        {
            get { return fCategoryId; }
            set { SetPropertyValue<int?>(nameof(CategoryId), ref fCategoryId, value); }
        }
    }

}
